<?php

function dna_generator_menu() {
  $items = array();
  $items['dna_generator'] = array(
    'title' => "DNA Generator",
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dna_generator_form'),
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );

  $items['dna_generator_success_page'] = array(
    'title' => "DNA Result!",
    'page callback' => 'dna_generator_success',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function dna_generator_form() {
  $form['dna_letters'] = array(
    '#title' => 'DNA Letters',
    '#type' => 'textfield',
    '#description' => t('enter the DNA nucleotides letters'),
    '#element_validate' => array('element_validate_input_letters'),
    '#required' => TRUE,
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Generate!',
  );

  return $form;
}

function element_validate_input_letters($element) {
  $array_string = str_split($element['#value']);

  foreach ($array_string as $letter) {
    if ($letter != "A" || $letter != "T" || $letter != "C" || $letter != "G") {
      form_error($element, t('DNA nucleotides must only consist of letters A, T, C, or G'));
      break;
    }
  }
}

function dna_generator_form_submit($form, &$form_state) {
  $input_string = $form_state['values']['dna_letters'];
  $result = dna_generator($input_string);
  $_SESSION['final_string'] = $result;
  $_SESSION['input'] = $input_string;
  $form_state['redirect'] = 'dna_generator_success_page';
}

function dna_generator($letters_string) {
  $array_letters = str_split($letters_string);
  $output_array = array();

  foreach ($array_letters as $letter) {
    if ($letter == "A") {
      array_push($output_array, "T");
    } elseif ($letter == "T") {
      array_push($output_array, "A");
    } elseif ($letter == "C") {
      array_push($output_array, "G");
    } else {
      array_push($output_array, "C");
    }
  }

  $outout_string = implode("", $output_array);
  return $output_string;
}

function dna_generator_success() {
  $answer = $_SESSION['final_string'];
  $input = $_SESSION['input'];
  return 'Your input is: <strong>' . $input . '</strong>. The output DNA is: <strong>' . $answer . '</strong>.';
}
